# Generated by Django 5.2.14 on 2026-07-22 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("kam", "KAM"), ("business_twin", "Business Twin")],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("final", "Final"), ("non_final", "Non final")],
                        max_length=20,
                    ),
                ),
                ("schema_version", models.CharField(default="1.0", max_length=20)),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("data", models.JSONField()),
                ("rendered_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="ai_core.conversation",
                    ),
                ),
                (
                    "profile_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="ai_core.companyprofilesnapshot",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="ai_core.recommendationrecord",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "report_type", "input_fingerprint"),
                        name="unique_report_fingerprint",
                    )
                ],
            },
        ),
    ]
